"""Structured dev seed data for products, families, and suppliers."""

FAMILIES = (
    {"name": "Cement", "is_active": True},
    {"name": "Aggregates", "is_active": True},
    {"name": "Pipes", "is_active": True},
    {"name": "Steel", "is_active": True},
    {"name": "Timber", "is_active": True},
    {"name": "Tools", "is_active": True},
    {"name": "Electrical", "is_active": True},
    {"name": "Plumbing", "is_active": True},
    {"name": "Paint", "is_active": True},
    {"name": "Safety", "is_active": True},
    {"name": "Fasteners", "is_active": True},
    {"name": "Misc", "is_active": True},
    {"name": "Legacy stock", "is_active": False},
)

SUPPLIERS = (
    {
        "name": "BuildSupply Ltd",
        "phone": "+351 210 000 001",
        "contact_name": "Ana Ribeiro",
        "email": "sales@buildsupply.dev",
        "is_active": True,
    },
    {
        "name": "Porto Materials Co",
        "email": "sales@portomaterials.dev",
        "contact_name": "Carlos Mendes",
        "is_active": True,
    },
    {
        "name": "National Cement Works",
        "phone": "+351 220 000 002",
        "contact_name": "Warehouse desk",
        "is_active": True,
    },
    {
        "name": "Iberian Steel Trading",
        "phone": "+351 221 000 003",
        "contact_name": "Joao Silva",
        "is_active": True,
    },
    {
        "name": "Norte Timber Supply",
        "email": "orders@nortetimber.dev",
        "is_active": True,
    },
    {
        "name": "ElectroPorto",
        "phone": "+351 222 000 004",
        "contact_name": "Maria Costa",
        "is_active": True,
    },
    {
        "name": "AquaFlow Plumbing",
        "email": "supply@aquaflow.dev",
        "is_active": True,
    },
    {
        "name": "ColorWorks Paint",
        "phone": "+351 223 000 005",
        "is_active": True,
    },
    {
        "name": "SafeGuard Equipment",
        "contact_name": "Pedro Alves",
        "is_active": True,
    },
    {
        "name": "FixAll Fasteners",
        "email": "bulk@fixall.dev",
        "is_active": True,
    },
    {
        "name": "Old Suppliers Inc",
        "notes": "Inactive — do not order",
        "is_active": False,
    },
    {
        "name": "Closed Warehouse Deals",
        "notes": "Company closed",
        "is_active": False,
    },
)

# internal_code, description, family, unit, stock, price, reorder_level, is_active
PRODUCTS = (
    ("CEM-50", "Cement 50kg", "Cement", "kg", "100", "12.95", "20", True),
    ("CEM-25", "Cement 25kg", "Cement", "kg", "80", "7.50", "15", True),
    ("CEM-40", "Cement 40kg rapid", "Cement", "kg", "5", "10.20", "25", True),
    ("CEM-WHITE", "White cement 25kg", "Cement", "kg", "30", "18.00", "10", True),
    ("CEM-OLD", "Cement discontinued bag", "Cement", "kg", "2", "9.00", "0", False),
    ("SAND-1KG", "Sand 1kg", "Aggregates", "kg", "250.5", "0.85", "50", True),
    ("GRAVEL-10", "Gravel 10mm bulk", "Aggregates", "kg", "120", "0.45", "30", True),
    ("GRAVEL-20", "Gravel 20mm bulk", "Aggregates", "kg", "8", "0.50", "40", True),
    ("SAND-FINE", "Fine sand bag 25kg", "Aggregates", "kg", "60", "3.20", "0", True),
    ("SAND-OLD", "Old sand stock", "Aggregates", "kg", "10", "0.80", "0", False),
    ("PIPE-20", "Steel pipe 20mm", "Pipes", "m", "50", "8.75", "20", True),
    ("PIPE-32", "Steel pipe 32mm", "Pipes", "m", "35", "12.40", "15", True),
    ("PIPE-50", "PVC pipe 50mm", "Pipes", "m", "3", "6.90", "25", True),
    ("PIPE-OLD", "Obsolete pipe 15mm", "Pipes", "m", "5", "4.00", "0", False),
    ("STEEL-6", "Steel bar 6mm", "Steel", "m", "200", "2.10", "50", True),
    ("STEEL-8", "Steel bar 8mm", "Steel", "m", "150", "2.80", "40", True),
    ("STEEL-10", "Steel bar 10mm", "Steel", "m", "4", "3.50", "30", True),
    ("STEEL-PLATE", "Steel plate 2mm", "Steel", "m2", "25", "45.00", "10", True),
    ("STEEL-OLD", "Rusty steel bar 12mm", "Steel", "m", "8", "3.00", "0", False),
    ("TIMBER-2X4", "Timber 2x4 3m", "Timber", "m", "40", "5.60", "15", True),
    ("TIMBER-2X6", "Timber 2x6 3m", "Timber", "m", "30", "7.20", "10", True),
    ("TIMBER-PLY", "Plywood sheet 12mm", "Timber", "m2", "18", "22.00", "8", True),
    ("TIMBER-OLD", "Damaged timber bundle", "Timber", "m", "5", "4.00", "0", False),
    ("HAMMER", "Claw hammer 500g", "Tools", "piece", "25", "14.50", "5", True),
    ("DRILL-18", "Drill bit set 18pc", "Tools", "piece", "12", "29.99", "3", True),
    ("SAW-CIRC", "Circular saw blade 190mm", "Tools", "piece", "2", "18.00", "8", True),
    ("LEVEL-60", "Spirit level 60cm", "Tools", "piece", "15", "11.50", "0", True),
    ("TOOL-OLD", "Broken chisel set", "Tools", "piece", "3", "8.00", "0", False),
    ("CABLE-2.5", "Cable 2.5mm 100m", "Electrical", "m", "8", "89.00", "20", True),
    ("CABLE-1.5", "Cable 1.5mm 100m", "Electrical", "m", "12", "65.00", "15", True),
    ("SOCKET", "Double socket white", "Electrical", "piece", "50", "3.40", "20", True),
    ("SWITCH-1G", "Light switch 1 gang", "Electrical", "piece", "40", "2.80", "0", True),
    ("ELEC-OLD", "Old fuse box", "Electrical", "piece", "2", "15.00", "0", False),
    ("VALVE-15", "Ball valve 15mm", "Plumbing", "piece", "22", "6.50", "10", True),
    ("TAP-CHROME", "Chrome tap mixer", "Plumbing", "piece", "6", "34.00", "12", True),
    ("FIT-90", "Elbow fitting 90deg 20mm", "Plumbing", "piece", "3", "1.20", "50", True),
    ("PIPE-PEX", "PEX pipe 16mm", "Plumbing", "m", "100", "1.85", "0", True),
    ("PLUMB-OLD", "Leaky tap stock", "Plumbing", "piece", "4", "12.00", "0", False),
    ("PAINT-WHITE", "Interior paint white 10L", "Paint", "l", "20", "42.00", "8", True),
    ("PAINT-GRAY", "Exterior paint gray 10L", "Paint", "l", "15", "48.00", "6", True),
    ("PAINT-RED", "Metal paint red 2.5L", "Paint", "l", "2", "18.50", "10", True),
    ("PAINT-PRIMER", "Wood primer 5L", "Paint", "l", "10", "28.00", "0", True),
    ("PAINT-OLD", "Expired paint bucket", "Paint", "l", "3", "10.00", "0", False),
    ("GLOVES-L", "Work gloves size L", "Safety", "piece", "100", "2.50", "30", True),
    ("HELMET", "Safety helmet yellow", "Safety", "piece", "18", "12.00", "10", True),
    ("GOGGLES", "Safety goggles clear", "Safety", "piece", "5", "4.50", "15", True),
    ("VEST-HIVIS", "Hi-vis vest orange", "Safety", "piece", "30", "6.00", "0", True),
    ("SAFE-OLD", "Torn gloves batch", "Safety", "piece", "8", "1.50", "0", False),
    ("BOLT-M8", "Bolt M8 x 50 pack 100", "Fasteners", "piece", "45", "8.90", "20", True),
    ("NUT-M8", "Nut M8 pack 100", "Fasteners", "piece", "50", "4.20", "25", True),
    ("SCREW-50", "Wood screws 50mm box", "Fasteners", "piece", "3", "6.80", "30", True),
    ("WASHER-M8", "Washer M8 pack 100", "Fasteners", "g", "500", "0.02", "0", True),
    ("FAST-OLD", "Rusty bolt mix", "Fasteners", "piece", "10", "3.00", "0", False),
    ("TAPE-DUCT", "Duct tape 50m", "Misc", "piece", "24", "5.50", "10", True),
    ("GLUE-EPOXY", "Epoxy glue 2-part", "Misc", "piece", "15", "9.99", "0", True),
    ("ROPE-10", "Poly rope 10mm 50m", "Misc", "m", "12", "18.00", "5", True),
    ("CEMENT-MIX", "Ready-mix concrete 25kg", "Misc", "kg", "2", "14.00", "20", True),
    ("MISC-OLD", "Unknown hardware lot", "Misc", "piece", "6", "2.00", "0", False),
    ("LEG-001", "Legacy item A", "Legacy stock", "piece", "5", "1.00", "0", True),
    ("LEG-002", "Legacy item B", "Legacy stock", "piece", "3", "2.00", "0", True),
    ("LEG-003", "Legacy item C", "Legacy stock", "kg", "10", "0.50", "0", True),
)

PRODUCT_SUPPLIER_LINKS = (
    ("CEM-50", "BuildSupply Ltd"),
    ("CEM-50", "Porto Materials Co"),
    ("CEM-50", "National Cement Works"),
    ("CEM-25", "BuildSupply Ltd"),
    ("CEM-25", "National Cement Works"),
    ("CEM-40", "National Cement Works"),
    ("CEM-WHITE", "Porto Materials Co"),
    ("SAND-1KG", "BuildSupply Ltd"),
    ("GRAVEL-10", "Porto Materials Co"),
    ("GRAVEL-20", "BuildSupply Ltd"),
    ("SAND-FINE", "Porto Materials Co"),
    ("PIPE-20", "BuildSupply Ltd"),
    ("PIPE-20", "Iberian Steel Trading"),
    ("PIPE-32", "BuildSupply Ltd"),
    ("PIPE-50", "AquaFlow Plumbing"),
    ("STEEL-6", "Iberian Steel Trading"),
    ("STEEL-8", "Iberian Steel Trading"),
    ("STEEL-10", "Iberian Steel Trading"),
    ("STEEL-PLATE", "Iberian Steel Trading"),
    ("TIMBER-2X4", "Norte Timber Supply"),
    ("TIMBER-2X6", "Norte Timber Supply"),
    ("TIMBER-PLY", "Norte Timber Supply"),
    ("HAMMER", "BuildSupply Ltd"),
    ("DRILL-18", "BuildSupply Ltd"),
    ("SAW-CIRC", "FixAll Fasteners"),
    ("LEVEL-60", "BuildSupply Ltd"),
    ("CABLE-2.5", "ElectroPorto"),
    ("CABLE-1.5", "ElectroPorto"),
    ("SOCKET", "ElectroPorto"),
    ("SWITCH-1G", "ElectroPorto"),
    ("VALVE-15", "AquaFlow Plumbing"),
    ("TAP-CHROME", "AquaFlow Plumbing"),
    ("FIT-90", "AquaFlow Plumbing"),
    ("PIPE-PEX", "AquaFlow Plumbing"),
    ("PAINT-WHITE", "ColorWorks Paint"),
    ("PAINT-GRAY", "ColorWorks Paint"),
    ("PAINT-RED", "ColorWorks Paint"),
    ("PAINT-PRIMER", "ColorWorks Paint"),
    ("GLOVES-L", "SafeGuard Equipment"),
    ("HELMET", "SafeGuard Equipment"),
    ("GOGGLES", "SafeGuard Equipment"),
    ("VEST-HIVIS", "SafeGuard Equipment"),
    ("BOLT-M8", "FixAll Fasteners"),
    ("NUT-M8", "FixAll Fasteners"),
    ("SCREW-50", "FixAll Fasteners"),
    ("WASHER-M8", "FixAll Fasteners"),
    ("TAPE-DUCT", "BuildSupply Ltd"),
    ("GLUE-EPOXY", "BuildSupply Ltd"),
    ("ROPE-10", "BuildSupply Ltd"),
    ("CEMENT-MIX", "National Cement Works"),
)
