# Generated by Django 6.1 on 2026-08-18 11:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_inactive_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfamily',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='productfamily',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_productfamily_name_ci'),
        ),
    ]
