# Generated by Django 6.1 on 2026-08-18 11:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productfamily_name_ci'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_supplier_name_ci'),
        ),
    ]
